[package]
name = "molt-forked"
description.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true
keywords.workspace = true
authors.workspace = true
readme.workspace = true
repository.workspace = true
documentation.workspace = true

[dependencies]
indexmap.workspace = true
molt-macro.workspace = true
molt-syntax.workspace = true
num-bigint = { workspace = true, optional = true }
num-traits = { workspace = true, optional = true }
web-time = { workspace = true, optional = true }

[features]
default = []
full = ["dep:num-bigint", "dep:num-traits"]
wasm = ["std_buff", "dep:web-time"]
std_buff = []
