[package]
name = "molt-app"
description.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true
keywords.workspace = true
authors.workspace = true
readme.workspace = true
repository.workspace = true
documentation.workspace = true

[dependencies]
molt-forked = { workspace = true, default-features = false }
molt-shell = { workspace = true, default-features = false }

[features]
default = ["full"]
full = ["molt-forked/full", "molt-shell/full"]

[[bin]]
name = "moltsh"
path = "src/main.rs"
