[package]
name = "molt-wasm-demo"
description = "Demo of molt-wasm"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
molt-wasm.workspace = true
log = "0.4.6"
web-sys = { version = "0.3", features = ["Element"] }
wasm-logger = "0.2"
yew = { version = "0.21", features = ["csr"] }
yew_icons = {version = "0.8", features = ["BootstrapGithub","FeatherSun","FeatherMoon"]}

[build-dependencies]
chrono = "0.4"
