[package]
name = "molt-wasm-demo"
description = "Demo of molt-wasm"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
molt-wasm.workspace = true
log.workspace = true
web-sys = { workspace = true, features = ["Element"] }
wasm-logger.workspace = true
yew = { workspace = true, features = ["csr"] }
yew_icons = { workspace = true, features = ["bootstrap", "feather"] }

[build-dependencies]
chrono.workspace = true

[features]
default = []
full = ["molt-wasm/full"]
